// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhLWnb2QwGh1FnCTByQOsy5s0Qr8S0DAg',
    appId: '1:513701854891:web:06536814593964336b81ee',
    messagingSenderId: '513701854891',
    projectId: 'student-attendance-manag-3bbc4',
    authDomain: 'student-attendance-manag-3bbc4.firebaseapp.com',
    storageBucket: 'student-attendance-manag-3bbc4.firebasestorage.app',
    measurementId: 'G-WP0T95FT6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGrXTK3RVUN2G4GD0w82x1VA43MDOWWxA',
    appId: '1:513701854891:android:8ff20d2463a4f1606b81ee',
    messagingSenderId: '513701854891',
    projectId: 'student-attendance-manag-3bbc4',
    storageBucket: 'student-attendance-manag-3bbc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAklJEtW4oyaVUPiYASIrbwOUL-UK2y9KI',
    appId: '1:513701854891:ios:b246fe784eaefd476b81ee',
    messagingSenderId: '513701854891',
    projectId: 'student-attendance-manag-3bbc4',
    storageBucket: 'student-attendance-manag-3bbc4.firebasestorage.app',
    iosClientId: '513701854891-ju2av0rn8oiui894grlpa76lht01cgeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAklJEtW4oyaVUPiYASIrbwOUL-UK2y9KI',
    appId: '1:513701854891:ios:b246fe784eaefd476b81ee',
    messagingSenderId: '513701854891',
    projectId: 'student-attendance-manag-3bbc4',
    storageBucket: 'student-attendance-manag-3bbc4.firebasestorage.app',
    iosClientId: '513701854891-ju2av0rn8oiui894grlpa76lht01cgeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhLWnb2QwGh1FnCTByQOsy5s0Qr8S0DAg',
    appId: '1:513701854891:web:9572e5aee7325e8e6b81ee',
    messagingSenderId: '513701854891',
    projectId: 'student-attendance-manag-3bbc4',
    authDomain: 'student-attendance-manag-3bbc4.firebaseapp.com',
    storageBucket: 'student-attendance-manag-3bbc4.firebasestorage.app',
    measurementId: 'G-JF51Q2LHYT',
  );

}